### ISSUE TITLE
Can not modify System API resource due to request validation error

### ISSUE THREAD

**Issue by CalMlynarczyk** [auth0/terraform-provider-auth0#315]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I want to both manage and reference the default Management (AKA System) API that is created by default for every Auth0 tenant. Referencing this resource is useful for creating `auth0_client_grant` resources that give clients access to this API. The majority of the properties on this API resource can not by modified, compared to a custom-defined API. However, there are a couple of properties, including the token lifetime, that can be modified for this API.

Since this resource exists by default on every tenant and can not be deleted, I initially imported it into my Terraform state. I then copied all of the imported properties to my Terraform configuration file.

Applying this configuration works fine so long as the plan does not require a change to this API resource. However, if your plan modifies this System API resource, the `apply` step fails due to a request payload validation error:

```
Error: 400 Bad Request: Payload validation error: 'Additional properties not allowed: enforce_policies,token_lifetime_for_web,allow_offline_access,signing_alg,scopes,name'.

with auth0_resource_server.management
on main.tf line 1, in resource "auth0_resource_server" "management":
resource "auth0_resource_server" "management" {
```

I believe this is occurring because the called out payload properties can not be modified for the System API resource, but the Auth0 provider is including them in the request, even if I take them out of the configuration and only leave in the editable properties. I tested editing the token lifetime property by directly calling the server resource API, and if I exclude the properties that can not be modified from the request then it succeeds.

### Expectation

If I modify one of the editable properties on the System API and apply the changes, the Terraform run should complete without error.

As a "nice-to-have", I don't want to have to specify the values for the System API resource in my configuration that I can not modify, such as the scopes.

### Reproduction

Add the below resource to your Terraform configuration. I assume the correct way to set these values is to import the resource to your configuration since it will already exist on the tenant at creation time.

```tf
resource "auth0_resource_server" "management" {
  skip_consent_for_verifiable_first_party_clients = true
  token_lifetime                                  = 86400

  // START Immutable properties

  /* 
   * Removing the immutable properties from the configuration does not fix the issue;
   * these values will be in the state from the start since you always have to import this 
   * resource, so Terraform will assume removing them requires a modification to the
   * resource's state and include these properties with empty values in the request to the
   * Management API.
   */ 
  identifier                                      = "https://<tenant>.auth0.com/api/v2/"
  name                                            = "Auth0 Management API"

  scopes {
    description = "Blacklist Tokens"
    value       = "blacklist:tokens"
  }
  
  /* 
   * ...remaining pre-defined scopes...
   *
   * However, it might be advisable to not specify scopes for this resource, since they can
   * not be modified for the System API anyways and there are a lot of them.
   */

  // END Immutable properties
}
```

### Auth0 Terraform Provider version

0.37.0

### Terraform version

1.2.8

**Comment by sergiught** [comment]
Hey @CalMlynarczyk Thanks for the super detailed issue description! 👏🏻 This is somewhat related to https://github.com/auth0/terraform-provider-auth0/issues/14 which is an issue we're currently working on fixing. We're going to introduce new helper functions for each value type that will be able to more accurately distinguish between:
- an attribute not being present in the config
- an attribute being present in the config but set to the type's default empty value
- an attribute being present in the config and being set to an arbitrary value

I don't have an exact ETA but we should have this fixed within the next couple of weeks.

Thanks for your patience!

**Comment by sergiught** [comment]
Hey @CalMlynarczyk 👋🏻 I have a fix in https://github.com/auth0/terraform-provider-auth0/pull/374 for this. Once that gets reviewed and merged in, it will be available in the next release. If you wish you could also test the branch before it gets merged using the make install command, e.g. `make install VERSION=xx.xx.xx` and referencing the produced version in your tf config file:

```terraform
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "xx.xx.xx"
    }
  }
}
```

**Comment by sergiught** [comment]
Hey folks, we just released https://registry.terraform.io/providers/auth0/auth0/0.39.0 with a fix for this. We'll close the issue down now.

**Comment by CalMlynarczyk** [comment]
@sergiught Glad to hear; thanks for getting a fix out. I'll give it a try and report back if I'm still having any problems.
